# Android config
android.automationName=uiautomator2
android.platformName=android
android.appPackage=com.tuhuynh.sdetproecommerce
android.appActivity=host.exp.exponent.MainActivity

# iOS config
ios.automationName=XCUITest
ios.platformName=ios
ios.platformVersion=16.4
ios.deviceName=iPhone 14 Pro Max
ios.bundleId=com.tuhuynh.sdetproecommerce

# Appium server
appium.serverUrl=http://127.0.0.1:4723